### ISSUE TITLE
【开源项目】Ant Design Blazor 

### ISSUE THREAD

**Issue by SinnoSong** [DotNETWeekly-io/DotNetWeekly#156]
https://github.com/ant-design-blazor/ant-design-blazor

A rich set of enterprise-class UI components based on Ant Design and Blazor.
WebAssembly static hosting examples:https://antblazor.com/

**Comment by gaufung** [comment]
![image](https://user-images.githubusercontent.com/11272110/177692175-55589150-c0cb-433e-b807-2bbfa2ae24ae.png)

Ant Design Blazor 是基于 `Ant Design` 和 `Blazor` 的 UI 应用框架，支持 `.NET 3.1` 以上版本，并且各种主流浏览器。

**Comment by gaufung** [comment]
![image](https://github.com/DotNETWeekly-io/DotNetWeekly/assets/11272110/a768edd7-d2fd-4526-a4b9-e2e96db57229)
