### ISSUE TITLE
【开源项目】C# 实现神经网络

### ISSUE THREAD

**Issue by gaufung** [DotNETWeekly-io/DotNetWeekly#158]
https://rubikscode.net/2022/07/04/implementing-simple-neural-network-in-c/

**Comment by gaufung** [comment]
![image](https://user-images.githubusercontent.com/11272110/179327270-3d233efb-b60d-4b6d-a559-3c75274bb35c.png)

神经网络是目前人工智能的支持体系，虽然说现在流行的框架比如 `PyTourch`, `TensorFlow` 使我们不需要关心神经网络的具体实现，但是从头到尾实现一个神经网络可以是我们的基础更加牢固。这篇文章介绍了如何用 C# 实现一个神经网络，并且复习神经网络的基本知识。

**Comment by SinnoSong** [comment]
应该属于文章推荐类别

**Comment by gaufung** [comment]
![image](https://github.com/DotNETWeekly-io/DotNetWeekly/assets/11272110/b1333648-06e7-475f-b71d-36b9c37aeccb)
