### ISSUE TITLE
【文章推荐】如何选择 `.NET` 版本

### ISSUE THREAD

**Issue by gaufung** [DotNETWeekly-io/DotNetWeekly#159]
https://www.youtube.com/watch?v=55UdBNRuQ7k&ab_channel=NickChapsas

**Comment by gaufung** [comment]
![image](https://user-images.githubusercontent.com/11272110/179327689-a99bf95e-ca09-44fc-bb60-bd36f5b77436.png)

**Comment by gaufung** [comment]
微软公司选择在每年的 11 月份发布新的 `.NET` 版本，主要分为两种类型
- Long Term Support (LTS): 长期支持版本，通常为偶数版，比如 `.NET 6`
- Current: 是当前版本，通常为奇数版，比如 `.NET 5`.

除此之外，还有一个版本叫做 `Preview`, 它是与发布版，通常是社区喜欢尝鲜的用户提前体验新的功能。 但是很多人有一种这样的固有观点：

> 只使用 LTS 的版本

其实是不对的，除了 `Preview` 版本，`Current` 和 `LTS` 都有一定的支持时间，分别为 3 年和 18 个月。在这期间，这些版本会得到完全的支持，比如功能提升，安全漏洞升级等等。在后续的 6 月期间，只有维护支持，通常只有安全漏洞升级。按照微软的版本支持政策，只要定期升级版本，就能得到完整的支持。而且使用新的版本，比如从 `.NET Core 3.1` 迁移到 `.NET 5`, 会得到很大的性能上的提升，而且几乎没有任何 break change.

**Comment by fanxiao92** [comment]
> 
Current 和 LTS 都有一定的支持时间，分别为 18 个月和 3 年
