### ISSUE TITLE
一点问题

### ISSUE THREAD

**Issue by SinnoSong** [DotNETWeekly-io/DotNetWeekly#170]
1. 期数问题
查看项目从开始到现在，多的时候一个月可以完成4期，但是大部分时候都是2期。是否可以修改为半月一刊，在每月月中，月底发布。
2. 贡献问题
如何参加项目贡献？只能提交Issue，然后由项目创建者完成每期内容编辑？

**Comment by gaufung** [comment]
> 查看项目从开始到现在，多的时候一个月可以完成4期，但是大部分时候都是2期。是否可以修改为半月一刊，在每月月中，月底发布。

是的，有时候工作和休假的原因，没有时间每周发布。

> 如何参加项目贡献？只能提交Issue，然后由项目创建者完成每期内容编辑？ 

如果你有兴趣加入进来，可以考虑增加其他贡献方式，比如发布期刊

**Comment by gaufung** [comment]
@SinnoSong  Has invited you as the owner of this organization.

**Comment by SinnoSong** [comment]
@gaufung ok
