### ISSUE TITLE
【文章推荐】.NET SDK将提供内置容器支持

### ISSUE THREAD

**Issue by SinnoSong** [DotNETWeekly-io/DotNetWeekly#218]
[Announcing built-in container support for the .NET SDK](https://devblogs.microsoft.com/dotnet/announcing-builtin-container-support-for-the-dotnet-sdk/)

**Comment by gaufung** [comment]
![image](https://user-images.githubusercontent.com/11272110/189487357-76fe268c-dad2-4a0a-a016-40842ffd40cd.png)

在 .NET 诞生之初，它就对 `Container` 做了大量的支持。虽然我们可以通过 `Dockerfile` 来配置，但是新的 `.NET` SDK 已经内置了对它的支持，比如在 `csproj` 文件中配置相关信息。
