### ISSUE TITLE
【文章推荐】MAUI Blazor App 教程

### ISSUE THREAD

**Issue by gaufung** [DotNETWeekly-io/DotNetWeekly#238]
https://www.c-sharpcorner.com/article/build-a-blazor-hybrid-app-with-net-maui-for-cross-platform-application/

**Comment by SinnoSong** [comment]
在本文中介绍了下列内容：
- 什么是Hybrid Blazor App
- 什么是.NET MAUI
- .NET MAUI Blazor app
- 开始使用 .NET MAUI Blazor App
- .NET MAUI Blazor App 的先决条件
- 使用 Visual Studio 创建 .NET MAUI Blazor 应用
- 在 Windows 中运行和测试 .NET MAUI Blazor 应用
- 在 Android 模拟器中运行并测试 .NET MAUI Blazor 应用
- 为什么要使用 .NET MAUI Blazor 应用
  - 使用Blazor，我们可以同时使用 .NET 和 C# 来构建前端 Web UI 和后端逻辑
  - 我们可以对前端Web UI 和后端逻辑使用相同的 C# 技能集，这将加速开发并降低成本。
  - 我们不需要对使用哪些前端框架而感到疑惑。
  - 我们可以开发 .NET MAUI for Windows、安卓、iOS、macOS、Web 的跨平台应用程序。
  - 适用于跨平台应用的相同 C# 和 .NET
  - 共享代码和 UI 布局
  - 共享设计和一致的 UI
  - 共享相同的逻辑，测试
  - 适用于所有平台的原生应用
  - 可以使用Windows或Mac 进行开发，并且可以在每个设备上运行
  - 我们可以使用单个项目，这将易于维护和工作
  - 我们可以使用所有 .NET 库和 C# 特性
  - 最新技术和强大的社区支持
