### ISSUE TITLE
【开源项目】grpc

### ISSUE THREAD

**Issue by SinnoSong** [DotNETWeekly-io/DotNetWeekly#242]
[grpc](https://github.com/grpc/grpc)

gRPC 是一个现代的、开源的、高性能的远程过程调用 (RPC) 框架并且可以在任何地方运行。 gRPC 使客户端和服务器应用程序能够透明地通信，而且简化了连接之间系统的构建。

**Comment by gaufung** [comment]
Sorry. Look like it's not related to .NET. Too big topic is not sutiable in this project.
