### ISSUE TITLE
【开源项目】MAUI

### ISSUE THREAD

**Issue by SinnoSong** [DotNETWeekly-io/DotNetWeekly#253]
[.NET Multi-platform App UI (.NET MAUI)](https://github.com/dotnet/maui)是一个框架，用于在单个代码库中使用 C# 和 XAML 构建新式、多平台、本机编译的 iOS、Android、macOS 和 Windows 应用。

**Comment by gaufung** [comment]
From my perspective, this topic is too big to learn. I prefer the tiny topic

**Comment by SinnoSong** [comment]
You are right.
