### ISSUE TITLE
【行业资讯】.NET MAUI 支持 Xcode 14 和 iOS 16

### ISSUE THREAD

**Issue by SinnoSong** [DotNETWeekly-io/DotNetWeekly#271]
[.NET MAUI 支持 Xcode 14 和 iOS 16](https://devblogs.microsoft.com/dotnet-ch/%e5%ae%98%e5%ae%a3-net-maui-%e6%94%af%e6%8c%81-xcode-14-%e5%92%8c-ios-16/)

**Comment by gaufung** [comment]
![image](https://user-images.githubusercontent.com/11272110/201470554-b500aa55-d536-4ab8-9a21-9e03f753315b.png)

.NET MAUI 正式支持 Xcode 14 和 iOS 16
