### ISSUE TITLE
【文章推荐】 函数式编程

### ISSUE THREAD

**Issue by SinnoSong** [DotNETWeekly-io/DotNetWeekly#306]
[Erik Meijer - 函数编程基础知识](https://learn.microsoft.com/zh-cn/shows/c9-lectures-erik-meijer-functional-programming-fundamentals)

**Comment by gaufung** [comment]
![image](https://user-images.githubusercontent.com/11272110/209458122-5842c253-23e4-4063-aec7-04830027302f.png)

Erik Meijer 博士介绍的函数式编程课程。
