### ISSUE TITLE
【文章推荐】C# Clean Architecture

### ISSUE THREAD

**Issue by gaufung** [DotNETWeekly-io/DotNetWeekly#360]
https://blog.ndepend.com/clean-architecture-for-asp-net-core-solution/

**Comment by gaufung** [comment]
![image](https://user-images.githubusercontent.com/11272110/224476505-3e01c667-4437-443d-a199-1a146fe61c9c.png)

对于 `ASP.NET Core` 的应用程序，如遵循 `Clean Architecture` 的设计原则的话，应该是这么组织解决方案的。
![image](https://user-images.githubusercontent.com/11272110/224476342-32a007b9-a7e3-4311-9f69-7de2f1d0cf7f.png)。

整个架构可以拆分为四个部分
- Domain
- Application
- WebUI
- Infrastructure 

它们之间遵循下面的设计规范
- 每一层只能外面依赖里卖弄
- 应用层只处理创建，编辑和持久化实体对象
- 基础设施保证可以更换
- UI 层包含 `Controller` 和 `View`

**Comment by gy0857478** [comment]
有沒有推薦的 Repository 可以參考呢？
