### ISSUE TITLE
【文章推荐】.NET 开发者期望社区毁灭？

### ISSUE THREAD

**Issue by gaufung** [DotNETWeekly-io/DotNetWeekly#599]
https://aaronstannard.com/dotnet-eventing-backslide/

**Comment by gaufung** [comment]
最近 `.NET 9 ` 开发计划中的一个 [Epic](https://github.com/dotnet/aspnetcore/issues/53219) 引来了巨大的讨论，它主要讨论是在 `.NET 9` 中引入事件框架。但是 `.NET` 社区中已经包含了很多这样的框架。这个给开发人员带来的疑问：为什么微软作为第一方为什么要吃掉开源社区的市场？
这篇文章的作者分析了这种现象，并且认为这种做法是伤害 `.NET` 社区的生态。

**Comment by tonyqus** [comment]
这个作者是Akka.NET作者，我一直关注，他对.NET开源生态的理解一直很独到，也很透彻。
https://aaronstannard.com/next-decade-dotnet/
