### ISSUE TITLE
【行业资讯】Powershell 讨论

### ISSUE THREAD

**Issue by gaufung** [DotNETWeekly-io/DotNetWeekly#623]
https://news.ycombinator.com/item?id=40204256

**Comment by gaufung** [comment]
![image](https://github.com/DotNETWeekly-io/DotNetWeekly/assets/11272110/53c2ddc2-5170-462f-b466-fb73f4298085)

Hack News 上关于 `Powershell` 的讨论，每个人都有自己的看法和偏好。

**Comment by tonyqus** [comment]
https://www.spiceworks.com/tech/tech-general/news/jeffrey-snover-quits-microsoft/
可以吃下这个瓜，不过这新闻是2年前的，我也是最近知道的
