### ISSUE TITLE
【行业资讯】Avalonia项目宣布离开.NET基金会

### ISSUE THREAD

**Issue by tonyqus** [DotNETWeekly-io/DotNetWeekly#628]
https://github.com/AvaloniaUI/Avalonia/discussions/14666

**Comment by gaufung** [comment]
![image](https://github.com/DotNETWeekly-io/DotNetWeekly/assets/11272110/ca12318a-e245-4d7c-b2e7-4d6484f05647)
 
Avalonia 团队宣布离开 `.NET Foundation` , 主要原因是想要让项目的主导权保留在开发核心团队。至于说具体的原因导致这次分手，声明中并没有说，不过这一篇[文章](https://www.glennwatson.net/posts/dnf-problems-solutions)指出的 `.NET Foundation` 存在的问题和解决方案。

**Comment by tonyqus** [comment]
我在.NET基金会呆了3年，目睹了很多无语的操作，说实话这个基金会问题是很多的，如果靠谱的话，生态不会是现在这样。还好微软.NET团队和DevDiv组还是比较给力，只是由微软主导，而非基金会主导，导致社会对于.NET误解还是很深的，特别是信任度方面。自从前年发生了HotReload Revert事件之后，对.NET基金会的信任度急剧下降，开发者终于明白原来是.NET组才有决策权，.NET基金会没有。

另外.NET基金会成立的背景比较特殊，当时是Xamarin和微软联合成立的，但是后面Xamarin被微软收购了，导致这个基金会实际有点虚了。
我之前写过一篇文章，https://zhuanlan.zhihu.com/p/682919116，其中有提到.NET开源的背景，他曾任.NET基金会Director，那可能是.NET最辉煌的几年。

**Comment by gaufung** [comment]
谢谢提供更多的背景。
