### ISSUE TITLE
【行业资讯】 加入 Microsoft Build 中 .NET 团队

### ISSUE THREAD

**Issue by gaufung** [DotNETWeekly-io/DotNetWeekly#630]
https://devblogs.microsoft.com/dotnet/join-the-dotnet-team-microsoft-build-2024/

**Comment by gaufung** [comment]
![image](https://github.com/DotNETWeekly-io/DotNetWeekly/assets/11272110/43a5200e-6bbe-425a-8851-27449cc0b566)

5 月 21 号到 23 号是一年一度的 Microsoft Build 大会。大会中会涉及到很多 `.NET` 相关的内容，包裹 `Aspire`,  `AI` 与 `.NET` 应用应用程序结合等等，如果感兴趣，可以线上加入。

**Comment by tonyqus** [comment]
这标题是不是有点歧义，是不是 应该翻译成 欢迎参加Build大会的.NET团队相关主题演讲
