### ISSUE TITLE
【建议】关于开辟知乎专栏的建议

### ISSUE THREAD

**Issue by tonyqus** [DotNETWeekly-io/DotNetWeekly#632]
我这两天仔细阅读了下这个周刊，和之前我找到的中国.NET Weekly不太一样，引用了大量国外最新的.NET资讯和项目，内容还是不错的，国内.NET社区的问题之一主要是消息太封闭，很多人并不看国外社区的文章，整天又抱怨国内没有好的内容可看，国内技术社区已经基本沦为水贴站和广告站。

目前这个周刊的发布平台流量比较有限，Github和你的个人网站都有点小众，我也是无意中逛Github看到这个周刊的。国内上Github是一个门槛（因为要翻墙，很多开发还真的不会翻墙，只用Gitee和国内平台）。从这个周刊的内容看，并没有涉及任何时政和敏感信息，放国内平台并不存在什么问题。

另外知乎作为一个问答类网站，审核尺度一直大于其他任何网站，而且比微信公众号流量更佳，我做过一些对比。

所以建议是否开辟一个知乎专栏，如果你MSFT的身份不太方便，我可以代劳。

**Comment by gaufung** [comment]
> 另外知乎作为一个问答类网站，审核尺度一直大于其他任何网站，而且比微信公众号流量更佳，我做过一些对比。
所以建议是否开辟一个知乎专栏，如果你MSFT的身份不太方便，我可以代劳。

可以，只要周刊内容能够指向 GitHub 站点就好

**Comment by gaufung** [comment]
早期的图片链接有的失效，我要解决一下，还有一些 typo 和语句也要调整。如果你愿意，可以把你加入这个 org。

**Comment by tonyqus** [comment]
图片放在Github确实可能被挡掉，知乎好像也不允许外链img，可能需要人工把图片复制过去。可以先发一期试试看，你用知乎吗？
我的知乎：https://www.zhihu.com/people/zhao-shi-de-hu-li

**Comment by gaufung** [comment]
> 知乎好像也不允许外链img

国内的互联网怎么变成这样，跳转个链接都要被阻止

**Comment by tonyqus** [comment]
> > 知乎好像也不允许外链img
> 
> 国内的互联网怎么变成这样，跳转个链接都要被阻止

安全可控呗，网站也是为了自保。如果用外链，有人故意换成标语或者违法广告怎么办？知乎已经是尺度比较大、能够发声的境内网站了，我都不用微博，实在太吓人了，什么都要审查。

**Comment by tonyqus** [comment]
有个小问题，之前incerry已经做了个[国内的.NET周报](https://zhuanlan.zhihu.com/p/697560878)了，我们要不要改个名字，以示区别，比如.NET环球周刊？

**Comment by gaufung** [comment]
有个担心是如果是周刊的话，这边的更新频率不能保证

**Comment by tonyqus** [comment]
对哦，你是月刊（虽然title是周刊），那就.NET环球月刊，一开始也没人在意，两月刊也无所谓。关于更新频率，社区应该没有这么苛刻，毕竟是用爱发电。另外我去看看，能不能再动员1-2小朋友来一起搞，人多力量大，小朋友可能有些其他诉求，比如评选微软MVP或者增加名气。

要不从2023年一月份那期（031期）开始发，太早的可能时效性有限，你觉得如何？

**Comment by gaufung** [comment]
可以，社区共同维护的话，负担小一点。

**Comment by tonyqus** [comment]
31期的图片怎么是挂的？我刚刚确认了下，好像不是我梯子的问题。
https://github.com/DotNETWeekly-io/DotNetWeekly/blob/master/docs/episode-031.md

**Comment by gaufung** [comment]
我周末把之前的图片链接都修复一下

**Comment by gaufung** [comment]
@tonyqus  已经修复

**Comment by tonyqus** [comment]
第一期发好了，https://zhuanlan.zhihu.com/p/698432811，请review

**Comment by tonyqus** [comment]
回过头来看，去年5月到现在，知乎专栏已完成全部期刊同步，效率还是可以的，哈哈哈。
