### ISSUE TITLE
【行业资讯】Twitter .NET团队成员列表

### ISSUE THREAD

**Issue by tonyqus** [DotNETWeekly-io/DotNetWeekly#638]
https://twitter.com/i/lists/120961876

总共95位MSFT

**Comment by gaufung** [comment]
![image](https://github.com/DotNETWeekly-io/DotNetWeekly/assets/11272110/9af91c03-b051-4ae7-b70c-91f494edddc3)

`.NET` 团队成员的 `Twitter` 账号列表。关注他们，获得最新的资讯。
