### ISSUE TITLE
【开源项目】币安.NET客户端库

### ISSUE THREAD

**Issue by tonyqus** [DotNETWeekly-io/DotNetWeekly#643]
https://github.com/JKorf/Binance.Net

https://www.nuget.org/packages/Binance.Net
下载量：1.3M
Star数：1k+

**Comment by gaufung** [comment]
![image](https://github.com/DotNETWeekly-io/DotNetWeekly/assets/11272110/d5bc7acd-a0b8-446b-90b9-abc9b5e4bb8d)

Binance.Net 是一个强类型的客户端库，用于访问 Binance 的 REST 和 Websocket API。所有数据都映射到可读的模型和枚举值。其他功能包括实现客户端订单簿维护、与其他交易所客户端库的轻松集成等。
