### ISSUE TITLE
【文章推荐】.NET 9 LINQ Performance Edition

### ISSUE THREAD

**Issue by tonyqus** [DotNETWeekly-io/DotNetWeekly#647]
https://steven-giesel.com/blogPost/783a404a-e39e-480f-bc99-a514a75d752d?utm_source=devdigest.today&utm_medium=website&utm_campaign=feature_promo&utm_content=link_click

**Comment by gaufung** [comment]
`.NET 9` 在 Linq 上继续有新的性能上的更新

- `Orderby.ToList` 

通过 `Vector` 这个 SIMD 指令集提升

- `Chunk` 

通过 `ReadOnlySpan` 提升性能


- `OfType` 

通过处理特定的类型而不是通用的类型

- `Any`

通过调用 `TryGetNonEnumeratedCount` 方法提高性能
