### ISSUE TITLE
【开源项目】Aspire GA

### ISSUE THREAD

**Issue by gaufung** [DotNETWeekly-io/DotNetWeekly#652]
https://devblogs.microsoft.com/dotnet/dotnet-aspire-general-availability/

**Comment by tonyqus** [comment]
昨天也看到这个了，但感觉Aspire不一定能起来。微服务在国外已经开始被打倒了，我看过一些相关文章，微服务过度增加了系统的复杂性和云成本

**Comment by gaufung** [comment]
![image](https://github.com/DotNETWeekly-io/DotNetWeekly/assets/11272110/769b0423-5f9f-40a3-9038-0220cb54fb8d)

最近在 `Build` 大会中，`Aspire` 这个项目已经处于 `GA` 状态，也就是可以可以尝试使用。
