### ISSUE TITLE
【开源项目】WireMock的.NET实现

### ISSUE THREAD

**Issue by tonyqus** [DotNETWeekly-io/DotNetWeekly#657]
https://github.com/WireMock-Net/WireMock.Net

WireMock 是一个Http 模拟服务，其核心也是一个web服务，WireMock主要是为特定请求提供固定的返回值。

WireMock可以作为单独进程启动，模拟一个WEB服务器，提供一些API访问，并返回特定的返回值。也可以作为第三方库在项目中使用。

关于WireMock，可以参考https://wiremock.org/

**Comment by gaufung** [comment]
Duplicated: https://github.com/DotNETWeekly-io/DotNetWeekly/issues/592
