### ISSUE TITLE
【文章推荐】升级的你的 .NET 应用程序，以 AWS 为例

### ISSUE THREAD

**Issue by tonyqus** [DotNETWeekly-io/DotNetWeekly#660]
https://www.youtube.com/watch?v=zb7v3d7IgYs

很有创意的视频

**Comment by gaufung** [comment]
![image](https://github.com/DotNETWeekly-io/DotNetWeekly/assets/11272110/add62da1-461a-4472-97db-cdf9b17e975b)

如果说你的应用程序是 `.NET Framework` + `SQL Server` 的架构，并且部署在 `On premise` 上，那么你的应用程序就像**囚犯**一样：
- 受限于 `on-premise` 无法动态扩展
- 被 Windows 和 `SQL Server` 授权费用牵制
- 受困于服务器管理
- 受整体架构的限制

使用 `AWS` 和相关工作可以帮助解决上述问题
**阶段一**
- SQL Server 迁移到 SQL Server on EC2 
- 应用程序迁移到 Virtaul Machine (Amazon EC2) 或者 Windows Container (Amazon EKS)

**阶段二**
- 迁移 `.NET Framework` 到 `.NET Core` 
- 迁移 `SQL Server` 到开源数据库，比如 `Amazon Aurora`, `PostgreSQL` 或者 `MySQL`

**阶段三**
- 将服务进行微服务化，使用 `Linux Container` 
- 将数据库中特定服务中数据拆分，比如 `Amazon DynamoDB` 

**阶段四**
- 云原生重构，比如 `Serverless`, `Event-driven`
