### ISSUE TITLE
【开源项目】OFGB

### ISSUE THREAD

**Issue by tonyqus** [DotNETWeekly-io/DotNetWeekly#662]
https://github.com/xM4ddy/OFGB

**Comment by gaufung** [comment]
![image](https://github.com/DotNETWeekly-io/DotNetWeekly/assets/11272110/05bc8f19-d86d-4cd7-a37c-0acb9dc16955)

Window 11 在最新的一次更新中，包含了大量的广告，比如文件管理系统，开始菜单等等。这个开源工具可以一键关闭这些功能。
