### ISSUE TITLE
【行业资讯】关于Blazor流行度的讨论

### ISSUE THREAD

**Issue by tonyqus** [DotNETWeekly-io/DotNetWeekly#663]
https://www.reddit.com/r/dotnet/comments/18q5sbr/blazor_popularity/

**Comment by gaufung** [comment]
![image](https://github.com/DotNETWeekly-io/DotNetWeekly/assets/11272110/87f158b5-3a2f-4756-a042-9231fb659b9d)

`Reddit` 上有一个 `Blazor` 流行度的讨论，总体而言，有不少人在生产环境中使用 `Blazor`，也有一些人在尝试之后就放弃了使用。

**Comment by tonyqus** [comment]
我补了篇中文版：https://zhuanlan.zhihu.com/p/701472790
