### ISSUE TITLE
【开源项目】Rin

### ISSUE THREAD

**Issue by gaufung** [DotNETWeekly-io/DotNetWeekly#669]
https://github.com/mayuki/Rin

**Comment by BlueHtml** [comment]
最后更新时间是 3年前（2021年），不知道是不是放弃维护了？

**Comment by gaufung** [comment]
> 最后更新时间是 3年前（2021年），不知道是不是放弃维护了？

No idea.

**Comment by gaufung** [comment]
![image](https://github.com/DotNETWeekly-io/DotNetWeekly/assets/11272110/2a2079b6-e091-4ac0-b92f-4c25a3c487f9)

`Rin` 是一个 `ASP.NET Core` 的开源插件，它可以记录和展示每个 `Web API` 请求和响应的细节，以及时间线和 Trace 日志。

![image](https://github.com/DotNETWeekly-io/DotNetWeekly/assets/11272110/e00e749e-feff-4521-8a87-e47923c2ef2e)

**Comment by tonyqus** [comment]
应该是挂了，没关系，挂了也能参考

**Comment by tonyqus** [comment]
这作者还有个项目：https://github.com/mayuki/Cocona
