### ISSUE TITLE
【行业资讯】如何从一个传统.NET职位跳槽到一个新的.NET职位

### ISSUE THREAD

**Issue by tonyqus** [DotNETWeekly-io/DotNetWeekly#671]
https://www.reddit.com/r/dotnet/comments/1da6brw/how_to_break_out_of_legacy_net_jobs/

**Comment by gaufung** [comment]
![image](https://github.com/DotNETWeekly-io/DotNetWeekly/assets/11272110/599ea12b-ea74-4f8e-9427-dc323a725955)

这是 Reddit 上的一个的讨论，发起者是一位在 `.NET Framework` 上工作超过 9 年的开发者。当他尝试投递其他更加现代的 `.NET` 或者 Azure 相关的开发工作的时候，在面试结束后，并没有得到后续的回复。他的问题是该如何从传统的 `.NET` 职位跳槽到新的 `.NET` 职位。
社区给了很多建议
- 假装拥有现代 `.NET` 的技能
- 切换语言并不是一件很罕见的事情，我们应该适应它
- 可以在工作中，将小的组件逐步迁移到现代的 `.NET`
- ...
