### ISSUE TITLE
【行业资讯】一个资深.NET开发应该具备哪些技能？

### ISSUE THREAD

**Issue by tonyqus** [DotNETWeekly-io/DotNetWeekly#673]
https://www.reddit.com/r/dotnet/comments/1db9f0t/most_desirable_skills_for_experienced_net/

**Comment by gaufung** [comment]
![image](https://github.com/DotNETWeekly-io/DotNetWeekly/assets/11272110/9be2f5e1-ec9b-4eba-8494-8638f73634e3)
