### ISSUE TITLE
【开源项目】AWS .NET Developer Guides

### ISSUE THREAD

**Issue by tonyqus** [DotNETWeekly-io/DotNetWeekly#674]
https://github.com/aws-samples/aws-net-guides

**Comment by gaufung** [comment]
![image](https://github.com/DotNETWeekly-io/DotNetWeekly/assets/11272110/0d2cc084-8ec3-44c8-901b-8837c7e23a76)

如果你想在 `AWS` 上开发和部署自己的 `.NET` 应用程序，那么这个开源项目可以参考一下，它包含了几乎大部分 `AWS` 的服务，比如通信，容器化，部署，监控，存储等等。
