### ISSUE TITLE
【文章推荐】.NET 8中的Frozen Collection介绍

### ISSUE THREAD

**Issue by tonyqus** [DotNETWeekly-io/DotNetWeekly#679]
![image](https://github.com/DotNETWeekly-io/DotNetWeekly/assets/772561/3b9aade6-f99c-48ef-88d4-090ec150dba3)

In .NET 8, Frozen Collections are new collections that provide a unique level of performance optimization.

Currently, we have 𝗙𝗿𝗼𝘇𝗲𝗻𝗦𝗲𝘁 and 𝗙𝗿𝗼𝘇𝗲𝗻𝗗𝗶𝗰𝘁𝗶𝗼𝗻𝗮𝗿𝘆.

Once a collection is frozen, it becomes immutable, making it ideal for scenarios where the collection is initialized once and remains unmodified.

But how does it differ from immutable collections such as ImmutableHashSet and ImmutableDictionary?

**Comment by gaufung** [comment]
Duplicated
