### ISSUE TITLE
【文章推荐】针对初学者的.NET解决方案架构师学习路线

### ISSUE THREAD

**Issue by tonyqus** [DotNETWeekly-io/DotNetWeekly#690]
https://medium.com/@scholarhatblogs/net-solution-architect-roadmap-for-beginners-1f303aeb29c0

**Comment by gaufung** [comment]
![image](https://github.com/DotNETWeekly-io/DotNetWeekly/assets/11272110/71496315-5f6d-4f53-9e4d-497fab5b88c9)

如果你是一个架构师，当你负责一个项目的时候，并且选择 `.NET` 作为主要的技术栈。那么这篇文章的路线可以帮助你成长为一名合格的架构师
1. 理解架构师的角色的职责
2. .NET 解决方案的关键
- 编程语言
- 框架
- 数据访问
- 库和设计
- 云和部署
3. 前端
- Web 技术
4. 数据库关键
- 数据管理和授权
- 安全和合规
- 大数据分析
5. 云平台关键
- 云服务
- 云平台
- 云架构和设计
6. API 设计和集成
7. Docker 和 K8S
8. DevOps
