### ISSUE TITLE
【文章推荐】从 .NET 2.0 到 .NET 9 性能提升文章汇总

### ISSUE THREAD

**Issue by gaufung** [DotNETWeekly-io/DotNetWeekly#751]
https://x.com/Dave_DotNet/status/1851684712299077847

**Comment by gaufung** [comment]
![image](https://github.com/user-attachments/assets/2eeb1037-7fd7-44e9-ab49-d0cc1de910b7)

随着 `.NET` 开源，每一年 `.NET` 在性能上都有显著的提升，而且官方也提供详细的文章来阐述这些内容，这里整理了至今所有的有关的文章：

.NET 9
https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-9/

.NET 8
https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-8/

.NET 7
https://devblogs.microsoft.com/dotnet/performance_improvements_in_net_7/ 

.NET 6
https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-6/

.NET 5
https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-5/

.NET 3.0
https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-core-3-0/

.NET 2.1
https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-core-2-1/ 

.NET 2.0
https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-core/

**Comment by tonyqus** [comment]
前几天有外国网友评论，前面几个.net版本实现是不是加了delay(100)，笑死
