### ISSUE TITLE
【行业资讯】是否升级.NET 9还是等.NET 10的投票

### ISSUE THREAD

**Issue by tonyqus** [DotNETWeekly-io/DotNetWeekly#766]
https://x.com/Dave_DotNet/status/1856017668261724547

<img width="496" alt="image" src="https://github.com/user-attachments/assets/5268c04e-ff5c-4454-a6b5-f28f86608fba">

**Comment by gaufung** [comment]
是否升级最新的 `.NET 9`, 这个 Twitter Thread 下面有很多讨论。
