### ISSUE TITLE
【开源项目】Todo 

### ISSUE THREAD

**Issue by tonyqus** [DotNETWeekly-io/DotNetWeekly#767]
https://github.com/davidfowl/TodoApi

**Comment by gaufung** [comment]
来自 `.NET` 社区的 David Fowler 的开源 `.NET` 示范项目，包含了两个部分
- Todo.Web: 使用 ASP.NET Core 的 Blazor WASM 前端
- Todo.Api: 使用 ASP.NET Core API 后端和 Minmal APIs

通过这个简单项目，可以学习相关最佳实践。
