### ISSUE TITLE
【行业资讯】.NET Conf 2024 Session Youtube播放列表

### ISSUE THREAD

**Issue by tonyqus** [DotNETWeekly-io/DotNetWeekly#770]
https://www.youtube.com/playlist?list=PLdo4fOcmZ0oXeSG8BgCVru3zQtw_K4ANY

**Comment by gaufung** [comment]
![image](https://github.com/user-attachments/assets/390b3863-2b27-47fb-ac88-05e129ab7b9e)

2024 年 .NET Conf 已经结束了，这里的 YouTube 列表包含了今年所有的视频内容。
