### ISSUE TITLE
【开源项目】FileSignatures

### ISSUE THREAD

**Issue by tonyqus** [DotNETWeekly-io/DotNetWeekly#776]
https://github.com/neilharvey/FileSignatures

**Comment by gaufung** [comment]
![image](https://github.com/user-attachments/assets/419227ff-e062-468f-89e0-6d824dfe35a2)

我们在判断一个文件的类型的时候，不能只看文件的后缀名。但是每种文件的都会有一种特殊的字节来表明其类型，也叫做魔数（Magic Number)。 `FileSignatures` 这个开源库实现了大部分常见的类型，并且可以读取相关字节来判断类型。

```csharp
var inspector = new FileFormatInspector();
var stream = new FileStream("test.doc", FileMode.Open);
var format = inspector.DetermineFileFormat(stream);
Console.WriteLine(format.Extension);
```

比如这个文件的拓展类型是 `doc` 类型，但是实际上是 `xlsm` 类型文件，这个库可以精确的检测出来。
