### ISSUE TITLE
我发现被转载到知乎的周刊被添加了私人的微信群，这是符合转载规范的吗？

### ISSUE THREAD

**Issue by Mu1lsrarthaReoetdmted** [DotNETWeekly-io/DotNetWeekly#782]
![image](https://github.com/user-attachments/assets/a229b33b-2aa5-4be6-96af-f7d77bfe69ec)
![image](https://github.com/user-attachments/assets/86217185-2313-495a-8630-6f3b4d153f63)

**Comment by gaufung** [comment]
已经授权，这是没问题的

**Comment by tonyqus** [comment]
老乡，我是自己人.jpg
